name: "People Like Shine"
description: "Handmade Jewelry by Rachel Binagia"

# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000
url: "http://localhost:4000"
baseurl: ""

paginate: 10

# future: true
# markdown: rdiscount
# permalink: pretty
# pygments: true 



